### PR TITLE
feat(ui): Add anchor link to headings

### PR DESCRIPTION
**Pull request by samridht23**
added fragment identifier to titles so we can directly link the part of the docs and do not have to scroll the to find a particular heading

### CODE REVIEW

**Review by half0wl — CHANGES_REQUESTED** [review]
Thank you for the PR!

This throws an error for me locally:
```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

Do you happen to know why?

It also looks like anchors are getting nested:

ss 2023-05-04 at 12 53 19 AM

**Comment by samridht23** [comment]
I have addressed the hydration issue and removed the nested <a> tag in this pull request. That was caused by improper handling of server-side rendering and hydration of the component. Can you check if the issue still persist.

**Review by half0wl — APPROVED** [review]
Works, thank you!

**Comment by half0wl** [comment]
Resolves #250

**Comment by half0wl** [comment]
Resolves #246

**Pull request merged**
